name = "DashBase"
uuid = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
authors = ["Alexandr Romanenko <waralex@gmail.com>"]
version = "0.2.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
DashBasePlotlyBaseExt = "PlotlyBase"
DashBasePlotlyJSExt = "PlotlyJS"
DashBasePlotsExt = "Plots"

[compat]
JSON3 = "1"
Plots = "1"
julia = "1.6"
PlotlyBase = "0.8"
PlotlyJS = "0.18"
PackageExtensionCompat = "1"

[extras]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots", "PlotlyBase", "PlotlyJS", "PlotlyKaleido"]
