name = "DashBase"
uuid = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
authors = ["Alexandr Romanenko <waralex@gmail.com>"]
version = "1.0.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
DashBasePlotlyBaseExt = "PlotlyBase"
DashBasePlotlyJSExt = "PlotlyJS"
DashBasePlotsExt = "Plots"

[compat]
Aqua = "0.8"
JSON3 = "1"
PlotlyBase = "0.8"
PlotlyJS = "0.18"
PlotlyKaleido = "2"
Plots = "1"
Requires = "1.3"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "Plots", "PlotlyBase", "PlotlyJS", "PlotlyKaleido"]
